name: CI/CD Pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
            node-version: [17.x]

    steps:
        - uses: actions/checkout@v4
        - name: Install modules
        - run: npm intall
        - name: Build project
        - run: npm build
       
